apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
spec:
  generators:
  - list:
      elements:
      - appName: adservice
        valueFile: "values/adservice_values.yaml"
      - appName: cartservice
        valueFile: "values/cartservice_values.yaml"
      - appName: checkoutservice
        valueFile: "values/checkoutservice_values.yaml"
      - appName: currencyservice
        valueFile: "values/currencyservice_values.yaml"
      - appName: emailservice
        valueFile: "values/emailservice_values.yaml"
      - appName: frontend
        valueFile: "values/frontend_values.yaml"
      - appName: paymentservice
        valueFile: "values/paymentservice_values.yaml"
      - appName: productcatalogservice
        valueFile: "values/productcatalogservice_values.yaml"
      - appName: recommendationservice
        valueFile: "values/recommendationservice_values.yaml"
      - appName: redis
        valueFile: "values/redis_values.yaml"  
      - appName: shippingservice
        valueFile: "values/shippingservice_values.yaml"
        
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: git@github.com:egoist777/argocd-helm.git
        targetRevision: HEAD
        path: "argocd-helm/charts/{{appName}}"
        helm:
          releaseName: "{{appName}}"
          valueFiles:
          - "{{valueFile}}"
      destination:
        name: in-cluster
        namespace: microservices
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true